### ISSUE TITLE
Could not find com.alibaba:fastjson:1.1.27-android

### ISSUE THREAD

**Issue by huangminlinux** [weex-templates/weex-plugin-template#2]
## Environment
```
➜ weex --version
 - weexpack : v1.2.3
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
## Description
```
➜ weex plugin create my-weex-plugin
➜ cd my-weex-plugin
# open ./playground/android  with android studio3.0 
```
when building gradle and get Error:Failed to resolve: com.alibaba:fastjson:1.1.27-android

**Comment by erha19** [comment]
@huangminlinux maybe you should upgrade your weexpack by `weex update weexpack`, then run the create command again.

**Comment by huangminlinux** [comment]
```
weex --version
   v1.3.11
 - weexpack : v1.2.7
 - weex-builder : v0.4.0
 - weex-previewer : v1.5.1
```
get the same issue

**Comment by erha19** [comment]
@huangminlinux It can be work on my platform and my colleague's platform, it looks like a network issue, also we have fixed some lint warning on the project, see https://github.com/weex-templates/weex-plugin-template/pull/3, maybe you should choose a better network to have a try.
